version: '3.1'

secrets:
  mjordansdev_secrets:
    file: .secrets

services:
  # Backend
  mjordansdev-backend:
    image: ghcr.io/ni2be/mjordansdev-backend:latest
    restart: always
    environment:
      mjordansdev_secrets_FILE: /run/secrets/mjordansdev_secrets
      AllowedOrigins : "https://mjordans.dev;https://www.mjordans.dev"
    secrets:
      - mjordansdev_secrets
    ports:
      - '60001:80'
    networks:
      - mjordansdev-network
  # Wordpress
  mjordansdev-frontend:
    depends_on:
      - mjordansdev-backend
    image: ghcr.io/ni2be/mjordansdev-frontend:latest
    ports:
      - '60000:80'
    restart: always
    networks:
      - mjordansdev-network
networks:
  mjordansdev-network: