version: '3'

services:
  # Backend
  mjordansdev-backend:
    image: ghcr.io/ni2be/mjordansdev-backend:latest
    restart: always
    ports:
      - '60001:80'
    networks:
      - mjordansdev-network
  # Wordpress
  mjordansdev-frontend:
    depends_on:
      - mjordansdev-backend
    image: ghcr.io/ni2be/mjordansdev-frontend:latest
    ports:
      - '60000:80'
    restart: always
    networks:
      - mjordansdev-network
networks:
  mjordansdev-network: