export const projectsDummyData = () => {
    return [{
        "id": "49237ea7-c9a9-4d67-bf1c-176679388d58",
        "name": "Dummy Project 1",
        "description": "Elitr ea elitr duis erat est soluta et eos ut duis ipsum. Sed qui erat ut diam dolores dolore diam rebum sed lorem ut duo augue ut consequat. Eu elit amet diam et erat sit odio aliquyam duis nonumy autem sit takimata lorem adipiscing et. Dolor lorem sit. Facer diam eos erat no eum et. Ut at in et sanctus sit clita sed eros sed. Dolore tation esse sadipscing possim dolor. Amet amet erat qui et congue takimata odio consetetur diam duo lorem et dolor. Vel eos rebum nonumy magna dolor lorem sit sed. Gubergren et dolor ut est et nobis sed dolore autem sed voluptua takimata. Nonumy sea ut sanctus sit iriure vero est aliquyam blandit molestie minim aliquyam amet vulputate. Elitr et dolor labore nulla vel eirmod suscipit diam sea invidunt et nonummy justo invidunt commodo. At diam et duo ipsum. Eirmod erat sanctus ut justo consequat dolore ipsum at sanctus tation et consetetur nisl et possim at in. Dolores nonumy diam aliquyam no eros vel ut iriure invidunt. Dolor amet dolor dolores zzril. Accumsan ipsum invidunt sea duis lorem consetetur et eos aliquip sed consetetur consetetur vero rebum labore assum aliquyam. Magna ipsum sit. Est diam ea sit velit est takimata sed sed.",
        "imageUrls": [{ "id": "a3f87aab-6127-4263-b2b3-ebb1f6a95527", "name": "preview_image", "url": "images/projects/logo.png" }]
    },{
        "id": "519bf30c-c02f-4f7f-870e-2e08160794ae",
        "name": "Dummy Project 2",
        "description": "Elitr ea elitr duis erat est soluta et eos ut duis ipsum. Sed qui erat ut diam dolores dolore diam rebum sed lorem ut duo augue ut consequat. Eu elit amet diam et erat sit odio aliquyam duis nonumy autem sit takimata lorem adipiscing et. Dolor lorem sit. Facer diam eos erat no eum et. Ut at in et sanctus sit clita sed eros sed. Dolore tation esse sadipscing possim dolor. Amet amet erat qui et congue takimata odio consetetur diam duo lorem et dolor. Vel eos rebum nonumy magna dolor lorem sit sed. Gubergren et dolor ut est et nobis sed dolore autem sed voluptua takimata. Nonumy sea ut sanctus sit iriure vero est aliquyam blandit molestie minim aliquyam amet vulputate. Elitr et dolor labore nulla vel eirmod suscipit diam sea invidunt et nonummy justo invidunt commodo. At diam et duo ipsum. Eirmod erat sanctus ut justo consequat dolore ipsum at sanctus tation et consetetur nisl et possim at in. Dolores nonumy diam aliquyam no eros vel ut iriure invidunt. Dolor amet dolor dolores zzril. Accumsan ipsum invidunt sea duis lorem consetetur et eos aliquip sed consetetur consetetur vero rebum labore assum aliquyam. Magna ipsum sit. Est diam ea sit velit est takimata sed sed.",
        "imageUrls": [{ "id": "a3f87aab-6127-4263-b2b3-ebb1f6a95527", "name": "preview_image", "url": "images/projects/logo.png" }]
    },{
        "id": "c864bd96-ae74-4b9e-9899-5263aa4cc979",
        "name": "Dummy Project 3",
        "description": "Elitr ea elitr duis erat est soluta et eos ut duis ipsum. Sed qui erat ut diam dolores dolore diam rebum sed lorem ut duo augue ut consequat. Eu elit amet diam et erat sit odio aliquyam duis nonumy autem sit takimata lorem adipiscing et. Dolor lorem sit. Facer diam eos erat no eum et. Ut at in et sanctus sit clita sed eros sed. Dolore tation esse sadipscing possim dolor. Amet amet erat qui et congue takimata odio consetetur diam duo lorem et dolor. Vel eos rebum nonumy magna dolor lorem sit sed. Gubergren et dolor ut est et nobis sed dolore autem sed voluptua takimata. Nonumy sea ut sanctus sit iriure vero est aliquyam blandit molestie minim aliquyam amet vulputate. Elitr et dolor labore nulla vel eirmod suscipit diam sea invidunt et nonummy justo invidunt commodo. At diam et duo ipsum. Eirmod erat sanctus ut justo consequat dolore ipsum at sanctus tation et consetetur nisl et possim at in. Dolores nonumy diam aliquyam no eros vel ut iriure invidunt. Dolor amet dolor dolores zzril. Accumsan ipsum invidunt sea duis lorem consetetur et eos aliquip sed consetetur consetetur vero rebum labore assum aliquyam. Magna ipsum sit. Est diam ea sit velit est takimata sed sed.",
        "imageUrls": [{ "id": "a3f87aab-6127-4263-b2b3-ebb1f6a95527", "name": "preview_image", "url": "images/projects/logo.png" }]
    }]
}