name: Docker Image CI

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

env:
  REGISTRY: ghcr.io
  REGISTRY_PATH: ni2be
  IMAGE_NAME: mjordansdev-backend
  IMAGE_TAG: latest #0.0.${{ github.run_number }}
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
    
    - name: cosign
      uses: sigstore/cosign-installer@ced07f21fb1da67979f539bbc6304c16c0677e76
    
    - name: Docker Setup
      uses: docker/setup-buildx-action@v1
    
    - name: Docker Login
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Docker metadata
      id: meta
      uses: docker/metadata-action@v1
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      

    - name: Build the Docker image
      id: build-and-push
      uses: docker/build-push-action@v3.1.1
      with:
        push: 'true'# ${{ github.event_name != 'pull_request' }}
        tags: ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        labels: ${{ steps.meta.outputs.labels }}
        file: backend.dockerfile
        
    - name: Sign
      if: true#${{ github.event_name != 'pull_request' }}
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: cosign sign ${{ env.REGISTRY }}/${{ env.REGISTRY_PATH }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
      
      
